import React, { useCallback, useContext, useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Globals from '../../global.js';
import Icon from './Icon.jsx';
import { UserContext } from '../../UserContext';
import { useCommon, useLang } from '../../i18n';
import './NotificationBell.css';

/**
 * The in-app milestone feed.
 *
 * Only ever shows things that actually happened to this student — a goal
 * reached, a streak milestone, a subscription about to lapse. It is not a
 * marketing channel (see services/notificationService.js), which is what keeps
 * the badge worth looking at.
 *
 * Polls on mount and on window focus rather than on an interval: the events
 * behind these rows are generated by the student's own actions, so "when they
 * come back to the tab" is exactly when something new could exist.
 */
// Plain fetch, not axios — NotificationBell is rendered by Navbar, which is
// eagerly bundled (every route wraps its page in Layout → Navbar), so a
// static axios import here shipped the 34KB library to every visitor,
// including ones on public pages who are never signed in.
const postJson = (path, body, sessionToken) =>
    fetch(`${Globals.URL}${path}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${sessionToken}` },
        body: JSON.stringify(body),
    });

const NotificationBell = () => {
    const { user, sessionToken } = useContext(UserContext);
    const t = useCommon().notifications;
    const { dir } = useLang();
    const navigate = useNavigate();
    const [open, setOpen] = useState(false);
    const [items, setItems] = useState([]);
    const [unread, setUnread] = useState(0);
    const panelRef = useRef(null);

    const authed = !!(user && user.id && sessionToken);

    const load = useCallback(async () => {
        if (!authed) return;
        try {
            const url = new URL(`${Globals.URL}/api/notifications`);
            url.searchParams.set('username', user.username);
            const res = await fetch(url, { headers: { Authorization: `Bearer ${sessionToken}` } });
            const data = await res.json();
            if (!data?.success) return;
            setItems(data.notifications || []);
            setUnread(data.unreadCount || 0);
        } catch (_) {
            /* the bell is ambient — a failure must never surface to the student */
        }
    }, [authed, user, sessionToken]);

    useEffect(() => { load(); }, [load]);

    useEffect(() => {
        if (!authed) return;
        const onFocus = () => load();
        window.addEventListener('focus', onFocus);
        return () => window.removeEventListener('focus', onFocus);
    }, [authed, load]);

    // Close on outside click / Escape, same behaviour as the user menu next to it.
    useEffect(() => {
        if (!open) return;
        const onPointerDown = (e) => {
            if (panelRef.current && !panelRef.current.contains(e.target)) setOpen(false);
        };
        const onKeyDown = (e) => { if (e.key === 'Escape') setOpen(false); };
        document.addEventListener('mousedown', onPointerDown);
        document.addEventListener('keydown', onKeyDown);
        return () => {
            document.removeEventListener('mousedown', onPointerDown);
            document.removeEventListener('keydown', onKeyDown);
        };
    }, [open]);

    const markAllRead = async () => {
        // Optimistic: the badge clears immediately, because waiting on a round
        // trip to acknowledge your own click reads as a broken button.
        setUnread(0);
        setItems((prev) => prev.map((n) => ({ ...n, read: true })));
        try {
            await postJson('/api/notifications/read', { username: user.username }, sessionToken);
        } catch (_) { /* ignore */ }
    };

    const openItem = async (n) => {
        setOpen(false);
        if (!n.read) {
            setUnread((u) => Math.max(0, u - 1));
            setItems((prev) => prev.map((x) => (x.id === n.id ? { ...x, read: true } : x)));
            try {
                await postJson('/api/notifications/read', { id: n.id, username: user.username }, sessionToken);
            } catch (_) { /* ignore */ }
        }
        if (n.ctaUrl) navigate(n.ctaUrl);
    };

    const ago = (iso) => {
        const mins = Math.floor((Date.now() - new Date(iso).getTime()) / 60000);
        if (mins < 1) return t.justNow;
        if (mins < 60) return t.minutesAgo(mins);
        const hours = Math.floor(mins / 60);
        if (hours < 24) return t.hoursAgo(hours);
        return t.daysAgo(Math.floor(hours / 24));
    };

    if (!authed) return null;

    return (
        <div className={`notif${open ? ' notif-open' : ''}`} ref={panelRef} dir={dir}>
            <button
                type="button"
                className="notif-trigger"
                onClick={() => setOpen((v) => !v)}
                aria-haspopup="dialog"
                aria-expanded={open}
                aria-label={unread > 0 ? `${t.label} (${unread})` : t.label}
            >
                <Icon name="bell" size={18} />
                {unread > 0 && <span className="notif-badge">{unread > 9 ? '9+' : unread}</span>}
            </button>

            {open && (
                <div className="notif-panel" role="dialog" aria-label={t.title}>
                    <div className="notif-head">
                        <strong>{t.title}</strong>
                        {unread > 0 && (
                            <button type="button" className="notif-mark" onClick={markAllRead}>
                                {t.markAllRead}
                            </button>
                        )}
                    </div>

                    {items.length === 0 ? (
                        <p className="notif-empty">{t.empty}</p>
                    ) : (
                        <ul className="notif-list">
                            {items.map((n) => (
                                <li key={n.id} className={`notif-item${n.read ? '' : ' is-unread'}`}>
                                    <button type="button" onClick={() => openItem(n)}>
                                        <span className="notif-item-title">{n.title}</span>
                                        {n.body && <span className="notif-item-body">{n.body}</span>}
                                        <span className="notif-item-time">{ago(n.createdAt)}</span>
                                    </button>
                                </li>
                            ))}
                        </ul>
                    )}
                </div>
            )}
        </div>
    );
};

export default NotificationBell;
