// Generates src/ui/glyphs.generated.tsx from the website's Icon.jsx so the app
// uses exactly the same Lucide-style glyphs (24x24 grid, 2px strokes).
//   node scripts/gen-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const source = readFileSync(resolve(here, '../../my-react-app/src/components/common/Icon.jsx'), 'utf8').replace(/\r\n/g, '\n');

const start = source.indexOf('const PATHS = {');
const end = source.indexOf('\n};', start);
if (start < 0 || end < 0) throw new Error('could not find PATHS in Icon.jsx');
const block = source.slice(start, end).split('\n').slice(1);

const TAGS = { path: 'Path', circle: 'Circle', rect: 'Rect', line: 'Line', polyline: 'Polyline', ellipse: 'Ellipse' };
const used = new Set();
const entries = [];

for (const line of block) {
  const m = /^\s{4}('?)([\w-]+)\1:\s*(<>.*<\/>),\s*$/.exec(line);
  if (!m) continue; // comments, blank lines
  const [, , key, jsx] = m;
  let out = jsx;
  for (const [html, rn] of Object.entries(TAGS)) {
    out = out.replace(new RegExp(`<${html}(\\s|/)`, 'g'), (_, tail) => {
      used.add(rn);
      return `<${rn}${tail}`;
    });
  }
  out = out.replace(/fill="currentColor"/g, 'fill={color}');
  entries.push(`  ${JSON.stringify(key)}: (color) => ${out},`);
}

const file = `// GENERATED by scripts/gen-icons.mjs from my-react-app/src/components/common/Icon.jsx.
// Do not edit by hand: add glyphs to the website Icon.jsx (or EXTRA_GLYPHS in
// src/ui/Icon.tsx) and regenerate.
import type { ReactElement } from 'react';
import { ${[...used].sort().join(', ')} } from 'react-native-svg';

export const GLYPHS: Record<string, (color: string) => ReactElement> = {
${entries.join('\n')}
};
`;

writeFileSync(resolve(here, '../src/ui/glyphs.generated.tsx'), file);
console.log(`wrote ${entries.length} glyphs (${[...used].sort().join(', ')})`);
