const trialQuestions = [
    {
      "id": "6271",
      "question_text": "A 40-year-old man with a history of recurrent painful attacks affecting the right big toe, was diagnosed with gout and started on allopurinol. He is also a known case of psoriasis for several years. He presented to the clinic with recurrent joint pain affecting the right big toe, left ankle, and bilateral knees. He is using allopurinol regularly as prescribed but has no improvement in his joint pain. Examinations revealed he has active arthritis at the left ankle and knee joints bilaterally (see lab results). Which of the following is the most likely cause for his joint pain?",
      "option1": "Active pseudogout arthritis.",
      "option2": "Active gout arthritis.",
      "option3": "Psoriatic arthritis.",
      "option4": "Osteoarthritis.",
      "question_type": "medicine",
      "correct_option": "Psoriatic arthritis.",
      "source": "GameBoy"
    },
    {
      "id": "6272",
      "question_text": "A 28-year-old woman with systemic lupus erythematosus for 2 years on hydroxychloroquine 200 mg/day, prednisone 5 mg/day, and azathioprine 100 mg/day presented to the Emergency Room with sudden onset of lower limb weakness and urinary incontinence. Examination revealed she has paraplegia and hyperreflexia (see lab results). Which of the following is the most appropriate test to be done immediately?",
      "option1": "Lumbar puncture, MRI brain",
      "option2": "Lumbar puncture, CT brain",
      "option3": "Lumbar puncture, MRI spinal cord",
      "option4": "Lumbar puncture, MRI, MRA, and MRV of the brain",
      "question_type": "medicine",
      "correct_option": "Lumbar puncture, MRI spinal cord",
      "source": "GameBoy"
    },
    {
      "id": "6273",
      "question_text": "A 50-year-old man is complaining of pain affecting the wrist joints bilaterally, second and third proximal interphalangeal joints, and right knee joint for the last 4 months. His examination revealed active arthritis at both wrists and second and third proximal interphalangeal joints (see lab results). Which of the following is the most appropriate treatment?",
      "option1": "Methotrexate",
      "option2": "Methotrexate and sulfasalazine",
      "option3": "Methotrexate and hydroxychloroquine",
      "option4": "Methotrexate, hydroxychloroquine, and prednisone",
      "question_type": "medicine",
      "correct_option": "Methotrexate, hydroxychloroquine, and prednisone",
      "source": "GameBoy"
    },
    {
      "id": "6274",
      "question_text": "A 30-year-old woman with systemic lupus erythematosus is evaluated for right hip pain that started 3 weeks ago and occurs at night and with walking. Her current medications are azathioprine, hydroxychloroquine, prednisolone, and lisinopril for the last 5 years. Her examination was normal except for pain on internal rotation of the right hip. Laboratory tests including pelvic and left hip radiographs were normal. Which of the following is the most likely cause of hip pain?",
      "option1": "Active lupus arthritis",
      "option2": "Septic arthritis affecting right hip",
      "option3": "Avascular necrosis affecting right hip",
      "option4": "Degenerative changes affecting right hip",
      "question_type": "medicine",
      "correct_option": "Avascular necrosis affecting right hip",
      "source": "GameBoy"
    },
    {
      "id": "6275",
      "question_text": "A 60-year-old man complaining of right knee pain for several years that has increased over the last few months. He also has noticed frequent knee clicks. A diagnosis of osteoarthritis is suspected. Which of the following is the most appropriate to confirm the diagnosis?",
      "option1": "Bilateral knee X-rays.",
      "option2": "MRI of the right knee.",
      "option3": "No further investigation.",
      "option4": "Arthroscopy for the right knee.",
      "question_type": "medicine",
      "correct_option": "No further investigation.",
      "source": "GameBoy"
    },
    {
      "id": "6276",
      "question_text": "A 52-year-old man with rheumatoid arthritis for 12 years. His current treatment consists of methotrexate 15 mg weekly and adalimumab 40 mg/2 weeks. He presented to the clinic complaining of fever and shortness of breath for 1 week. His chest examination revealed coarse crackles over the lower part of the right lung (see lab results). Which of the following is the most appropriate action to be taken on this visit?",
      "option1": "Hold adalimumab and start antibiotics",
      "option2": "Hold methotrexate and start antibiotics",
      "option3": "Hold his current treatment and start antibiotics",
      "option4": "Continue his current treatment and start antibiotics",
      "question_type": "medicine",
      "correct_option": "Hold his current treatment and start antibiotics",
      "source": "GameBoy"
    },
    {
      "id": "6277",
      "question_text": "A 30-year-old man presented to the Emergency Department with an acute monoarthritis where joint aspiration was performed. Based on the presence of crystals in the synovial fluid, he was diagnosed with gout. Which of the following is the most likely type of the crystals seen?",
      "option1": "Needle-shaped, negatively birefringent",
      "option2": "Needle-shaped, weakly positively birefringent",
      "option3": "Rhomboidal-shaped, negatively birefringent",
      "option4": "Rhomboidal-shaped, weakly positively birefringent",
      "question_type": "medicine",
      "correct_option": "Needle-shaped, negatively birefringent",
      "source": "GameBoy"
    },
    {
      "id": "6278",
      "question_text": "A 30-year-old woman with a diagnosis of systemic lupus erythematosus who was maintained on mycophenolate mofetil 1 gm/day, hydroxychloroquine 200 mg/day, and prednisone 5 mg/day for the last 1 year. She has had inactive disease for more than 6 months. She is planning to get pregnant (see lab results). Which of the following is the most appropriate action at this time?",
      "option1": "Discontinue prednisone and start cyclosporine",
      "option2": "Discontinue hydroxychloroquine and start quinacrine",
      "option3": "Discontinue mycophenolate mofetil and start azathioprine",
      "option4": "Discontinue mycophenolate mofetil and start methotrexate",
      "question_type": "medicine",
      "correct_option": "Discontinue mycophenolate mofetil and start azathioprine",
      "source": "GameBoy"
    },
    {
      "id": "6279",
      "question_text": "A 61-year-old woman is evaluated for a left pulmonary nodule that was discovered incidentally 2 months ago. She is currently asymptomatic and has not had shortness of breath, fever, chills, weight loss, or night sweats. Medical history is otherwise unremarkable, and she takes no medications. She never smoked. Examination revealed no cervical or supraclavicular lymphadenopathy, and the lungs are clear to auscultation (see report). CT scan chest: Showed an 8 mm left lung nodule. Which of the following is the most appropriate next step in management?",
      "option1": "PET/CT scan",
      "option2": "Bronchoalveolar lavage",
      "option3": "Transthoracic lung biopsy",
      "option4": "Observation and regular follow-up",
      "question_type": "medicine",
      "correct_option": "Observation and regular follow-up",
      "source": "GameBoy"
    },
    {
      "id": "6280",
      "question_text": "A 63-year-old woman presented with exertional dyspnea for 8 months. She was diagnosed with COPD 3 years ago and has had 4 exacerbations in the last year. She completed pulmonary rehabilitation and quit smoking 2 years ago. Medications include long-acting B2 agonist, inhaled glucocorticoid, roflumilast, and albuterol as needed. Examination revealed no jugular venous distention; decreased breath sounds, a loud pulmonary component of S1 (see lab results and reports). Chest radiograph: Normal. Echocardiogram: Ejection fraction of 60%, no valvular or wall motion abnormalities, and estimated mean pulmonary artery pressure is 55 mmHg. Which of the following is the most appropriate treatment?",
      "option1": "Daily prednisone",
      "option2": "Long-term oxygen therapy",
      "option3": "Overnight pulse oximetry",
      "option4": "Repeat pulmonary rehabilitation",
      "question_type": "medicine",
      "correct_option": "Long-term oxygen therapy",
      "source": "GameBoy"
    },
    {
      "id": "7933",
      "question_text": "A 70-year-old man is brought to the clinic with an acute confusional state. On examination, he has postural hypotension and dry mucus membranes. Test Result Normal Value Calcium 3.41 2.15-2.62 mmol/L Which of the following is the most appropriate initial treatment?",
      "option1": "I.V. 0.9% sodium chloride",
      "option2": "I.V. sodium pamidronate",
      "option3": "Oral prednisolone",
      "option4": "I.V. furosemide",
      "question_type": "medicine",
      "correct_option": "I.V. 0.9% sodium chloride",
      "source": "Midgard"
    },
    {
      "id": "7934",
      "question_text": "A 67-year-old man is brought to the Emergency Department by his family with confusion and a decreased level of consciousness. The family reported his being feverish and feeling unwell for 2 days that was also associated with diarrhea and poor oral intake. The patient has bronchial asthma, hypertension, and an old myocardial infarction. He has not been able to take his regular medications for 2 days due to the acute illness. On examination, the JVP is not visible, heart sounds are normal, no cardiac murmurs, and lungs are clear with no rhonchi or crepitation. The patient's extremities are cold and peripheral pulses feeble (see report). Blood pressure 83/45 mmHg Heart rate 120 /min (regular) Respiratory rate 20 /min Oxygen saturation 95% (room air) ECG: Sinus tachycardia and evidence of an old inferior myocardial infarction. Which of the following is the most appropriate next step in management?",
      "option1": "IV boluses of normal saline",
      "option2": "Intravenous beta blockers",
      "option3": "Nasogastric tube feeding",
      "option4": "Dopamine infusion",
      "question_type": "medicine",
      "correct_option": "IV boluses of normal saline",
      "source": "Midgard"
    },
    {
      "id": "7935",
      "question_text": "A 68-year-old woman with history of heart failure, stroke and diabetes, admitted for hysterectomy. She was kept on normal saline due to poor oral intake. 2 days post-operation, the nurse noticed the patient pulse oximetry was dropping with respiratory distress. On lung auscultation, there was bilateral basal crepitations. Which of the following is the best action to prevent this complication?",
      "option1": "Cardiology and pulmonary consultation",
      "option2": "Oxygen by nasal cannula at 2 L/min",
      "option3": "Furosemide 40 mg iv on post-op day 1",
      "option4": "Daily reassessment of fluid status",
      "question_type": "medicine",
      "correct_option": "Daily reassessment of fluid status",
      "source": "Midgard"
    },
    {
      "id": "7936",
      "question_text": "A 78-year-old man presents with a 10-day history of intermittent colicky abdominal pain. The pain is low, central and seems to be worse after eating. He has no associated fever or vomiting but does feel nauseated when the pain is present. He says that prior to this episode he had hard stools once or twice a week that were difficult to pass. For the past several days, he has had only watery stools, several times a day. On examination, there is fullness in his left lower quadrant with nonspecific tenderness diffusely and no guarding or rebound. A urine dipstick is normal. Which of the following is the most likely diagnosis?",
      "option1": "Acute colitis",
      "option2": "Constipation",
      "option3": "Ureteric stone",
      "option4": "Urinary tract infection",
      "question_type": "medicine",
      "correct_option": "Constipation",
      "source": "Midgard"
    },
    {
      "id": "7937",
      "question_text": "Which of the following is the best exercise to improve the function of a 68-year-old woman?",
      "option1": "Walking",
      "option2": "Swimming",
      "option3": "Resistance training",
      "option4": "Stationary bicycling",
      "question_type": "medicine",
      "correct_option": "Resistance training",
      "source": "Midgard"
    },
    {
      "id": "7938",
      "question_text": "A 72-year-old man complains of difficulty in getting up from the chair for the last 3 months. History reveals he has controlled type 2 diabetes and long standing hypertension. Which of the following is the most leading type of injury in this patient?",
      "option1": "Road traffic accidents",
      "option2": "Fire-related injuries",
      "option3": "Gunshot wounds",
      "option4": "Falls",
      "question_type": "medicine",
      "correct_option": "Falls",
      "source": "Midgard"
    },
    {
      "id": "7939",
      "question_text": "A 65-year-old man who is asymptomatic and has no known allergies is seen for a general examination. What is the best approach for pneumococcus immunization?",
      "option1": "PPSV23",
      "option2": "PCV13 followed by PPSV23",
      "option3": "PPSV23 followed by PCV13",
      "option4": "No evidence supports vaccinating this patient",
      "question_type": "medicine",
      "correct_option": "PCV13 followed by PPSV23",
      "source": "Midgard"
    },
    {
      "id": "7940",
      "question_text": "A 64-year-old man presents to the clinic after having first episode of right knee pain for 2 weeks duration. He asks for a medicine to relieve his pain. He does not have any other symptoms apart from epigastric burning. He has no history of injury to the knee. Examination of knee is normal. Which is the most appropriate analgesic for this patient at this stage?",
      "option1": "Aspirin",
      "option2": "Codeine",
      "option3": "Ibuprofen",
      "option4": "Paracetamol",
      "question_type": "medicine",
      "correct_option": "Paracetamol",
      "source": "Midgard"
    },
    {
      "id": "7941",
      "question_text": "An 81-year-old woman reports low back pain that began after a forceful coughing episode. Lumbar radiographs reveal features of a lumbar compression fracture. Which of the following is the most appropriate initial step in her care?",
      "option1": "Prescribe nasal calcitonin",
      "option2": "Prescribe acetaminophen",
      "option3": "Admit for vertebroplasty",
      "option4": "Infuse zoledronate",
      "question_type": "medicine",
      "correct_option": "Prescribe acetaminophen",
      "source": "Midgard"
    },
    {
      "id": "7942",
      "question_text": "A 77-year-old woman with stage 3 chronic kidney disease and pain from osteoarthritis of the first carpometacarpal joint. Which of the following is the best initial treatment for her pain?",
      "option1": "Tendon-release surgery",
      "option2": "Splinting and occupational therapy",
      "option3": "Ibuprofen 800mg 3 times daily with food",
      "option4": "Glucocorticoid injection into the first carpometacarpal joint",
      "question_type": "medicine",
      "correct_option": "Splinting and occupational therapy",
      "source": "Midgard"
    },
    {
      "id": "1378",
      "question_text": "A 68-year-old woman with history of heart failure, stroke and diabetes, admitted for hysterectomy. She was kept on normal saline due to poor oral intake. 2 days post-operation, the nurse noted the patient pulse oxymetry was dropping with respiratory distress. On lung auscultation, there was bilateral basal crepitations. Which of the following is the best action to prevent this complication?",
      "option1": "Cardiology and pulmonary consultation",
      "option2": "Oxygen by nasal cannula at 2 L/min",
      "option3": "Furosemide 40 mg iv on post-op day 1",
      "option4": "Daily reassessment of fluid status",
      "question_type": "medicine",
      "correct_option": "Daily reassessment of fluid status",
      "source": "general"
    },
    {
      "id": "1379",
      "question_text": "A 78-year-old man presents with a 10-day history of intermittent colicky abdominal pain. The pain is low, central and seems to be worse after eating. He has no associated fever or vomiting but does feel nauseated when the pain is present. He says that prior to this episode he had hard stools once or twice a week that were difficult to pass. For the past several days, he has had only watery stools, several times a day. On examination, there is fullness in his left lower quadrant with nonspecific tenderness diffusely and no guarding or rebound. A urine dipstick is normal. Which of the following is the most likely diagnosis?",
      "option1": "Acute colitis",
      "option2": "Constipation",
      "option3": "Ureteric stone",
      "option4": "Urinary tract infection",
      "question_type": "medicine",
      "correct_option": "Constipation",
      "source": "general"
    },
    {
      "id": "1380",
      "question_text": "Which of the following is the best exercise to improve the function of a 68-year-old woman?",
      "option1": "Walking",
      "option2": "Swimming",
      "option3": "Resistance training",
      "option4": "Stationary bicycling",
      "question_type": "medicine",
      "correct_option": "Resistance training",
      "source": "general"
    },
    {
      "id": "1381",
      "question_text": "A 72-year-old man complains of difficulty in getting up from the chair for the last 3 months. History reveals he has controlled type 2 diabetes and long standing hypertension. Which of the following is the most leading type of injury in this patient?",
      "option1": "Road traffic accidents",
      "option2": "Fire-related injuries",
      "option3": "Gunshot wounds",
      "option4": "Falls",
      "question_type": "medicine",
      "correct_option": "Falls",
      "source": "general"
    },
    {
      "id": "1382",
      "question_text": "A 65-year-old man who is asymptomatic and has no known allergies is seen for a general examination. What is the best approach for pneumococcus immunization?",
      "option1": "PPSV23",
      "option2": "PCV13 followed by PPSV23",
      "option3": "PPSV23 followed by PCV13",
      "option4": "No evidence supports vaccinating this patient",
      "question_type": "medicine",
      "correct_option": "PCV13 followed by PPSV23",
      "source": "general"
    },
    {
      "id": "1383",
      "question_text": "A 64-year-old man presents to the clinic after having first episode of right knee pain for 2 weeks duration. He asks for a medicine to relieve his pain. He does not have any other symptoms apart from epigastric burning. He has no history of injury to the knee. Examination of knee is normal. Which is the most appropriate analgesic for this patient at this stage?",
      "option1": "Aspirin",
      "option2": "Codeine",
      "option3": "Ibuprofen",
      "option4": "Paracetamol",
      "question_type": "medicine",
      "correct_option": "Paracetamol",
      "source": "general"
    },
    {
      "id": "1384",
      "question_text": "An 81-year-old woman reports low back pain that began after a forceful coughing episode. Lumbar radiographs reveal features of a lumbar compression fracture. Which of the following is the most appropriate initial step in her care?",
      "option1": "Prescribe nasal calcitonin",
      "option2": "Prescribe acetaminophen",
      "option3": "Admit for vertebroplasty",
      "option4": "Infuse zoledronate",
      "question_type": "medicine",
      "correct_option": "Prescribe acetaminophen",
      "source": "general"
    },
    {
      "id": "1385",
      "question_text": "A 77-year-old woman with stage 3 chronic kidney disease and pain from osteoarthritis of the first carpometacarpal joint. Which of the following is the best initial treatment for her pain?",
      "option1": "Tendon-release surgery",
      "option2": "Splinting and occupational therapy",
      "option3": "Ibuprofen 800mg 3 times daily with food",
      "option4": "Glucocorticoid injection into the first carpometacarpal joint",
      "question_type": "medicine",
      "correct_option": "Splinting and occupational therapy",
      "source": "general"
    },
    {
      "id": "1386",
      "question_text": "Which of the following physical maneuvers is most likely to assist the risk of future falls for a healthy 68-year-old man?",
      "option1": "Test for nystagmus",
      "option2": "Get-up-and-go test",
      "option3": "Test for pulsus paradoxus",
      "option4": "Lumbar spine flexibility test",
      "question_type": "medicine",
      "correct_option": "Get-up-and-go test",
      "source": "general"
    },
    {
      "id": "1387",
      "question_text": "A 75-year-old man with difficulty walking and left-sided leg weakness due to osteoarthritis of the hip. In which hand should a cane be used by this patient?",
      "option1": "Left hand",
      "option2": "Right hand",
      "option3": "Either hand",
      "option4": "Both hands simultaneously",
      "question_type": "medicine",
      "correct_option": "Right hand",
      "source": "general"
    },
    {
      "id": "5878",
      "question_text": "A 27-year-old woman presented at full term at labor, she was having uncontrolled diabetes during this pregnancy. Which of the following neonatal complications will most likely increase?",
      "option1": "Hyperglycemia",
      "option2": "Low Hemoglobin",
      "option3": "Low erythropoietin levels",
      "option4": "Respiratory distress syndrome",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Respiratory distress syndrome",
      "source": "GameBoy"
    },
    {
      "id": "5879",
      "question_text": "A primipara presents 1 week after delivery. She is tearful, has spells of crying, and lacks appetite and sleep. Which of the following is the most likely diagnosis?",
      "option1": "Anemia",
      "option2": "Schizophrenia",
      "option3": "Manic disorders",
      "option4": "Postnatal depression",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Postnatal depression",
      "source": "GameBoy"
    },
    {
      "id": "5880",
      "question_text": "A 30-year-old Primigravida at 17 weeks of gestation is known to have epilepsy and is on valproic acid. She was concerned about the possible risks to her baby. Which of the following fetal abnormalities is markedly increased?",
      "option1": "Oligohydramnios",
      "option2": "Polyhydramnios",
      "option3": "Neural tube defect",
      "option4": "Non-immune hydrops",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Neural tube defect",
      "source": "GameBoy"
    },
    {
      "id": "5881",
      "question_text": "A 28-year-old Primigravida at 8 weeks of gestation is known to have chronic hypertension and presented to Antenatal Clinic. Which of the following antihypertensive medications is contraindicated?",
      "option1": "Labetalol",
      "option2": "Nifedipine",
      "option3": "Lisinopril",
      "option4": "Methyldopa",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Lisinopril",
      "source": "GameBoy"
    },
    {
      "id": "5882",
      "question_text": "A 28-year-old G4 P3 AO at 12 weeks of gestation with a prior history of preeclampsia and fetal growth restriction presented to the Antenatal Clinic. Which of the following will most likely reduce the risk of growth restriction and preeclampsia?",
      "option1": "Aspirin",
      "option2": "Progesterone",
      "option3": "Multivitamins",
      "option4": "Ferrous sulfate",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Aspirin",
      "source": "GameBoy"
    },
    {
      "id": "5883",
      "question_text": "A 22-year-old G2 PO Al at 13 weeks of gestation presented to the Antenatal Clinic. In her first pregnancy, she had a painless fetal passage at 22 weeks. Which of the following interventions is most recommended for the current pregnancy?",
      "option1": "Aspirin",
      "option2": "Folic acid",
      "option3": "Cervical cerclage",
      "option4": "Regular antenatal visits with no specific intervention",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Cervical cerclage",
      "source": "GameBoy"
    },
    {
      "id": "5884",
      "question_text": "A 30-year-old Primigravida is found to have hyperthyroidism during her pregnancy. Which of the following is the most contraindicated?",
      "option1": "Propranolol",
      "option2": "Methimazole",
      "option3": "Thyroidectomy",
      "option4": "Radioactive iodine",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Radioactive iodine",
      "source": "GameBoy"
    },
    {
      "id": "5885",
      "question_text": "A 28-year-old Primigravida presented to the Antenatal Clinic for an Ultrasound scan. Ultrasound: Single viable fetus with significant lower levels of amniotic fluid (oligohydramnios). Which of the following is the most likely cause?",
      "option1": "Chorioangioma",
      "option2": "Duodenal atresia",
      "option3": "Diabetes mellitus",
      "option4": "Placental insufficiency",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Placental insufficiency",
      "source": "GameBoy"
    },
    {
      "id": "5886",
      "question_text": "A 36-year-old presented to the Antenatal Clinic for an Ultrasound scan. Ultrasound: Single viable fetus with significant increased levels of amniotic fluid (polyhydramnios). Which of the following is the most likely cause?",
      "option1": "Anencephaly",
      "option2": "Post-term pregnancy",
      "option3": "Posterior urethral valve",
      "option4": "Maternal ingestion of NSAID",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Anencephaly",
      "source": "GameBoy"
    },
    {
      "id": "5887",
      "question_text": "A pregnant woman with prenatal diagnosis of Rhesus (Rh) alloimmunization had an ultrasound scan during follow-up. Which of the following is the most diagnostic sign?",
      "option1": "Thin placenta",
      "option2": "Fetal bradycardia",
      "option3": "Fetal ascites with skin edema",
      "option4": "Low fetal middle cerebral artery (MCA) Doppler peak systolic velocity",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Fetal ascites with skin edema",
      "source": "GameBoy"
    },
    {
      "id": "6495",
      "question_text": "A 28-year-old woman G3 P0020 at 5 weeks' gestation presents with vaginal bleeding associated with some blood clots that has started 3 hours ago. She had been diagnosed with cervical incompetence in her 2 prior second-trimester abortions. A history of dilation and curettage in her last abortion declared. On examination; the cervical os is open and no on-going bleeding. Which of the following is the most likely cause of her current diagnosis of vaginal bleeding?",
      "option1": "Luteal phase defect",
      "option2": "Asherman's syndrome",
      "option3": "Cervical incompetence",
      "option4": "Chromosomal abnormality",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Chromosomal abnormality",
      "source": "Midgard"
    },
    {
      "id": "6496",
      "question_text": "A 35-year-old pregnant woman at 34 weeks of gestation presented with labour pains. On physical examination, the cervix was 4 cm dilated. Cardiotocography was performed (see image), Blood pressure 135/88 mmHg Heart rate 89 /min Respiratory rate 18 /min Temperature 37.4Â° C Which of the following is the most likely diagnosis?",
      "option1": "Placenta previa",
      "option2": "Head compression",
      "option3": "Umbilical cord compression",
      "option4": "Uteroplacental insufficiency",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Uteroplacental insufficiency",
      "source": "Midgard"
    },
    {
      "id": "6497",
      "question_text": "A 21-year-old woman G2 P1001 presents to the Emergency Room with a severe lower abdominal pain for 1 day. Pain is dull and intermittent that last for 10-15 minutes and associated with nausea and vomiting. Examination confirms tenderness and guarding in the lower abdomen, it is more on right side and slight fullness in the right iliac fossa (see report). Blood pressure 90/60 mmHg Heart rate 110 /min Respiratory rate 13 /min Temperature 3t.6Â° C Pregnancy Test: Negative. Which of the following is the most likely diagnosis?",
      "option1": "Acute cysts",
      "option2": "Ovarian torsion",
      "option3": "Acute appendicitis",
      "option4": "Ectopic pregnancy",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Ovarian torsion",
      "source": "Midgard"
    },
    {
      "id": "6498",
      "question_text": "A 28-year-old woman is diagnosed with an ectopic pregnancy. Which of the following is the most likely predisposing factor?",
      "option1": "Induction of ovulation",
      "option2": "Previous tubal pregnancy",
      "option3": "Pelvic inflammatory disease",
      "option4": "Use of an intrauterine contraceptive device",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Pelvic inflammatory disease",
      "source": "Midgard"
    },
    {
      "id": "6499",
      "question_text": "A 33-year-old pregnant woman G4 P2012 at 38 weeks' gestation presented with a complaint of dizziness, light-headedness and fainting sensation especially in bed for 2 weeks duration (see lab results). Blood pressure 110/70 mmHg Heart rate 100 min Respiratory rate 24 /min Temperature 36.6Â° C Test Result Normal Values Hb 95 120-160 g/L WBC 9 4.5-10.5 x 109/L Platelet count 200 150-400 x 109/L Which of the following is the best management?",
      "option1": "Blood transfusion",
      "option2": "Refer to a neurologist",
      "option3": "Avoid sleep on the back",
      "option4": "ECG and echocardiography",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Avoid sleep on the back",
      "source": "Midgard"
    },
    {
      "id": "6500",
      "question_text": "A 25-year-old woman has delivered a boy. On inspection of the umbilical cord, a single artery was noticed. Which of the following is associated with the above finding?",
      "option1": "African race",
      "option2": "Maternal diabetes",
      "option3": "Low foetal mortality",
      "option4": "Major foetal malformation in 80%",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Maternal diabetes",
      "source": "Midgard"
    },
    {
      "id": "6501",
      "question_text": "A 23-year-old primigravida presented in labour. The midwife advised mediolateral episiotomy during the 2nd stage of labour. What is the advantage of a mediolateral episiotomy?",
      "option1": "Easy repair",
      "option2": "Less infection",
      "option3": "Tighter introitus",
      "option4": "Less anal extension",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Less anal extension",
      "source": "Midgard"
    },
    {
      "id": "6502",
      "question_text": "A 23-year-old G2 P1001 at 22 weeks' gestation presented with a complaint of her abdomen is larger than her previous pregnancy (see report). Ultrasound: Showed dizygotic twin pregnancy. Which of the following best described membranes and placenta of dizygotic twins?",
      "option1": "Monochorionic and monoamniotic for conjoined twins",
      "option2": "Monochorionic and diamniotic for the fetuses of same sex",
      "option3": "Dichorionic and monoamniotic for the fetuses of same sex",
      "option4": "Dichorionic and diamniotic regardless of the sex of the fetuses",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Dichorionic and diamniotic regardless of the sex of the fetuses",
      "source": "Midgard"
    },
    {
      "id": "6503",
      "question_text": "A 28-year-old woman G 4 P2012 immigrant presented to the Maternal Health Clinic at 20 weeks' gestation with a cough and night chills for the past month. The cough is productive and produces thick sputum. She had been prescribed treatment by a general practitioner for the cough and it had not responded to treatment. Patient nail beds and conjunctiva appeared pale and the cervical lymph nodes are palpable. Auscultation of the chest shows crepitation over the upper left lobe. She had received a BC vaccine as a child. A blood test is positive for interferon-gamma release assays. Blood pressure 110/t0 mmHg Heart rate 84 /min Respiratory rate 18 /min Temperature 3t.5Â° C oral Which of the following is the next best step in obtaining a definitive diagnosis?",
      "option1": "Chest X-ray",
      "option2": "Sputum culture",
      "option3": "Tuberculin skin test",
      "option4": "Sputum smear cytology",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Sputum culture",
      "source": "Midgard"
    },
    {
      "id": "6504",
      "question_text": "A 28-year-old woman with mild intermittent asthma presents to the Health Clinic at 24 weeks' gestation and says that her symptoms have worsened as the pregnancy progresses. Prior to the pregnancy, she had an occasional exacerbation of asthma and used only an albuterol inhaler for treatment as needed. However, she now complains of daily symptoms and once per week symptoms at night time. A forced expiratory volume in 1 second test shows 70% of normal. Which of the following medication regimen is now most appropriate?",
      "option1": "Short-acting bronchodilators and oral glucocorticoids",
      "option2": "Inhaled glucocorticoids and short-acting bronchodilators",
      "option3": "Inhaled glucocorticoids and long-acting bronchodilators",
      "option4": "Long acting beta2 agonist and inhaled glucocorticoids",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Inhaled glucocorticoids and long-acting bronchodilators",
      "source": "Midgard"
    },
    {
      "id": "733",
      "question_text": "A 28-year-old woman G3 P0020 at 5 weeks gestation presents with vaginal bleeding and clots. History of cervical incompetence and prior second-trimester losses. Cervix open, no ongoing bleeding. Most likely cause?",
      "option1": "Luteal phase defect",
      "option2": "Asherman's syndrome",
      "option3": "Cervical incompetence",
      "option4": "Chromosomal abnormality",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Chromosomal abnormality",
      "source": "general"
    },
    {
      "id": "734",
      "question_text": "A 35-week pregnant woman at 34 weeks gestation presents in labor. Cervix 4 cm dilated. CTG shows late decelerations. Most likely diagnosis?",
      "option1": "Placenta previa",
      "option2": "Head compression",
      "option3": "Umbilical cord compression",
      "option4": "Uteroplacental insufficiency",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Uteroplacental insufficiency",
      "source": "general"
    },
    {
      "id": "736",
      "question_text": "A 28-year-old woman diagnosed with ectopic pregnancy. Most likely predisposing factor?",
      "option1": "Induction of ovulation",
      "option2": "Previous tubal pregnancy",
      "option3": "Pelvic inflammatory disease",
      "option4": "Use of intrauterine contraceptive device",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Pelvic inflammatory disease",
      "source": "general"
    },
    {
      "id": "737",
      "question_text": "A 33-year-old pregnant woman G4 P2012 at 38 weeks presents with dizziness and light-headedness. Labs: Hb = 95 g/L. Most appropriate management?",
      "option1": "Blood transfusion",
      "option2": "Refer to neurologist",
      "option3": "Avoid sleep on the back",
      "option4": "ECG and echocardiography",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Avoid sleep on the back",
      "source": "general"
    },
    {
      "id": "738",
      "question_text": "A 25-year-old woman delivers a baby with single umbilical artery. Which is associated with this nding?",
      "option1": "African race",
      "option2": "Maternal diabetes",
      "option3": "Low fetal mortality",
      "option4": "Major fetal malformation in 80%",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Maternal diabetes",
      "source": "general"
    },
    {
      "id": "739",
      "question_text": "A 23-year-old primigravida undergoes mediolateral episiotomy during second stage of labor. What is the advantage of this type of episiotomy?",
      "option1": "Easy repair",
      "option2": "Less infection",
      "option3": "Tighter introitus",
      "option4": "Less anal extension",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Less anal extension",
      "source": "general"
    },
    {
      "id": "740",
      "question_text": "A 23-year-old G2 P1001 at 22 weeks presents with larger abdomen than previous pregnancy. Ultrasound confirms dizygotic twins. Which describes membranes and placenta?",
      "option1": "Monochorionic and monoamniotic for conjoined twins",
      "option2": "Monochorionic and diamniotic for same-sex twins",
      "option3": "Dichorionic and monoamniotic for same-sex twins",
      "option4": "Dichorionic and diamniotic regardless of sex",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Dichorionic and diamniotic regardless of sex",
      "source": "general"
    },
    {
      "id": "741",
      "question_text": "A 28-year-old immigrant woman at 20 weeks presents with cough, night chills, and pale conjunctiva. Sputum thick and productive. IGRA positive. Next best step for de nitive diagnosis?",
      "option1": "Chest X-ray",
      "option2": "Sputum culture",
      "option3": "Tuberculin skin test",
      "option4": "Sputum smear cytology",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Sputum culture",
      "source": "general"
    },
    {
      "id": "742",
      "question_text": "A 28-year-old woman with mild intermittent asthma reports worsening symptoms during pregnancy. Uses albuterol occasionally pre-pregnancy. Now has daily symptoms and weekly nocturnal episodes. FEV1 = 70%. Most appropriate medication regimen?",
      "option1": "Short-acting bronchodilators and oral glucocorticoids",
      "option2": "Inhaled glucocorticoids and short-acting bronchodilators",
      "option3": "Inhaled glucocorticoids and long-acting bronchodilators",
      "option4": "Long-acting beta2 agonist and inhaled glucocorticoids",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Inhaled glucocorticoids and long-acting bronchodilators",
      "source": "general"
    },
    {
      "id": "743",
      "question_text": "A 34-year-old multiparous woman at 28 weeks presents with cough, clear sputum, bilateral rhonchi, and allergies. Most appropriate initial diagnostic test?",
      "option1": "Spirometry",
      "option2": "Chest X-ray",
      "option3": "Arterial blood gas levels",
      "option4": "Hemoglobin estimation",
      "question_type": "obstetrics and gynecology",
      "correct_option": "Spirometry",
      "source": "general"
    },
    {
      "id": "993",
      "question_text": "A 3-year-old girl presents to the Emergency Department with vaginal bleeding and pain. Her mother reports that she has been passing stools in her pants for 2 weeks despite being toilet trained. On examination, there is bruises on with blood staining labia majora. Which of the following is the most likely diagnosis?",
      "option1": "Sexual abuse",
      "option2": "Herpetic vaginitis",
      "option3": "Precocious puberty",
      "option4": "Gonorrheal vaginitis",
      "question_type": "pediatric",
      "correct_option": "Sexual abuse",
      "source": "GameBoy"
    },
    {
      "id": "1071",
      "question_text": "A 14-year-old child presented to the clinic after being sexually abused 6 hours earlier. Genital examination confirmed anogenital erythema and mild bleeding vaginally, and labia majora was swollen and bruised. What is the most likely site of hymeneal tear that is suggestive of penile penetration?",
      "option1": "2 o'clock",
      "option2": "4 o'clock",
      "option3": "6 o'clock",
      "option4": "8 o'clock",
      "question_type": "pediatric",
      "correct_option": "6 o'clock",
      "source": "GameBoy"
    },
    {
      "id": "1121",
      "question_text": "A pediatrician is called to attend a caesarean section delivery of 38 week's gestation baby. On delivery, the neonate does not cry immediately, appears cyanotic and floppy. After drying suctioning and stimulating the baby under the radiant warmer, the following evidence is recorded at 5 minutes. Heart rate 120 bpm, Breathing: Irregular, gasping, Reflex irritability: Coughs, and cries with stimulation, Activity: Arms and legs flexed, little movement, Appearance: Rosy with blue extremities. What is the most accurate Apgar score?",
      "option1": "6",
      "option2": "7",
      "option3": "8",
      "option4": "9",
      "question_type": "pediatric",
      "correct_option": "8",
      "source": "GameBoy"
    },
    {
      "id": "1137",
      "question_text": "A 12-year-old obese girl brought by her mother, 5-month after her menarche with irregular menstrual bleeding and increased weight. She has mild acne. The patient was uncomfortable, agitated and unable to cooperate to physical examination. BMI 26 kg/mÂ². What is the most likely disorder to be considered in communicating with this patient?",
      "option1": "Mood",
      "option2": "Anxiety",
      "option3": "Behavior",
      "option4": "Substance use",
      "question_type": "pediatric",
      "correct_option": "Anxiety",
      "source": "GameBoy"
    },
    {
      "id": "2313",
      "question_text": "According to Saudi vaccination program, which disease is effectively prevented in children?",
      "option1": "Q-fever",
      "option2": "Japanese encephalitis",
      "option3": "Herpes encephalitis",
      "option4": "Haemophilus influenza meningitis",
      "question_type": "pediatric",
      "correct_option": "Haemophilus influenza meningitis",
      "source": "GameBoy"
    },
    {
      "id": "2314",
      "question_text": "Recommended vaccines for a 6-year-old in Saudi Arabia?",
      "option1": "MMR, DTP, OPV",
      "option2": "MMR, HBV, DTP, HAV",
      "option3": "MMR, varicella, DTP, OPV",
      "option4": "MMR, varicella, OPV, PCV",
      "question_type": "pediatric",
      "correct_option": "MMR, varicella, DTP, OPV",
      "source": "GameBoy"
    },
    {
      "id": "2315",
      "question_text": "Newborn of HBsAg+ mother needs within 12 hours:",
      "option1": "Hep B vaccine only",
      "option2": "Hep B immunoglobulins only",
      "option3": "Both vaccine and immunoglobulins",
      "option4": "Test HBsAg first",
      "question_type": "pediatric",
      "correct_option": "Both vaccine and immunoglobulins",
      "source": "GameBoy"
    },
    {
      "id": "2316",
      "question_text": "18-month-old on antibiotics for tonsillitis but improving. Vaccination decision?",
      "option1": "Vaccinate as scheduled",
      "option2": "Wait until antibiotics finished",
      "option3": "Postpone OPV only",
      "option4": "Skip DTP",
      "question_type": "pediatric",
      "correct_option": "Vaccinate as scheduled",
      "source": "GameBoy"
    },
    {
      "id": "2317",
      "question_text": "14-year-old never had chickenpox or vaccine. Vaccination plan?",
      "option1": "No vaccination",
      "option2": "1 dose varicella",
      "option3": "2 doses 4 weeks apart",
      "option4": "3 doses at 0,1,6 months",
      "question_type": "pediatric",
      "correct_option": "2 doses 4 weeks apart",
      "source": "GameBoy"
    },
    {
      "id": "2318",
      "question_text": "Most important food allergy to note before flu vaccine?",
      "option1": "Chicken",
      "option2": "Shellfish",
      "option3": "Eggs",
      "option4": "Nuts",
      "question_type": "pediatric",
      "correct_option": "Eggs",
      "source": "GameBoy"
    },
    {
      "id": "7176",
      "question_text": "Which of the following measures would decrease the incidence of Sudden Infant Death Syndrome?",
      "option1": "Pacifier at bedtime",
      "option2": "Sleep in prone position",
      "option3": "Soft sleeping mattress",
      "option4": "Sleep position support device",
      "question_type": "pediatric",
      "correct_option": "Pacifier at bedtime",
      "source": "Midgard"
    },
    {
      "id": "7177",
      "question_text": "Which of the following is the most common cause of dehydration in children?",
      "option1": "Heat stroke",
      "option2": "Food poisoning",
      "option3": "Gastroenteritis",
      "option4": "Drugs side effects",
      "question_type": "pediatric",
      "correct_option": "Gastroenteritis",
      "source": "Midgard"
    },
    {
      "id": "7178",
      "question_text": "A 5-year-old child presents to Emergency Room with vomiting and diarrhea for 4 days. On examination, he looks dehydrated, hypoactive with sunken eyes, doughy skin and dry mucous membrane. The capillary refill is 4 seconds. Blood pressure 90/70 mmHg Heart rate 130 /min Respiratory rate 22 /min Temperature 36.6 Â°C Oxygen saturation 95 % Which of the following is the expected serum sodium level based on clinical finding?",
      "option1": "Low",
      "option2": "High",
      "option3": "Normal",
      "option4": "No correlation",
      "question_type": "pediatric",
      "correct_option": "High",
      "source": "Midgard"
    },
    {
      "id": "7179",
      "question_text": "A 5-year-old child presents to Emergency Room with vomiting and diarrhea for 4 days. On examination, he looks dehydrated, hypoactive with sunken eyes and delayed skin turgor with dry mucous membrane and capillary refill is 4 seconds. The child connected to cardiopulmonary monitor and IV access attained, blood sample sent for electrolytes. Blood pressure 60/40 mmHg Heart rate 134 /min Respiratory rate 23 /min Temperature 36.6 Â°C Oxygen saturation 95 % Which of the following is the most appropriate next action?",
      "option1": "Start inotropes",
      "option2": "Give 5% albumin bolus",
      "option3": "20 ml per kg normal saline bolus",
      "option4": "Start maintenance fluid waiting for serum electrolytes",
      "question_type": "pediatric",
      "correct_option": "20 ml per kg normal saline bolus",
      "source": "Midgard"
    },
    {
      "id": "7180",
      "question_text": "A 2-month-old infant found dead at his bed. According to the mother, he was feeding normally with usual activity. No history of fever or other abnormality. On examination, no sign of trauma or bruises on the skin. Baby gram was negative for fracture. Which of the following history's part is important to make the diagnosis?",
      "option1": "Social history",
      "option2": "Allergic history",
      "option3": "Blood transfusion history",
      "option4": "Maternal Medication history during pregnancy",
      "question_type": "pediatric",
      "correct_option": "Social history",
      "source": "Midgard"
    },
    {
      "id": "7181",
      "question_text": "A 2-month-old infant found dead at his bed. According to the mother, he was feeding normally with usual activity. No history of fever or other abnormality. On examination, no sign of trauma or bruises on the skin. Baby gram was negative for fracture. Mother is divorced and known smoker. Which of the following is the most likely diagnosis?",
      "option1": "Child abuse syndrome",
      "option2": "Maternal smoking syndrome",
      "option3": "Sudden infant death syndrome",
      "option4": "Apparent life threatening events",
      "question_type": "pediatric",
      "correct_option": "Sudden infant death syndrome",
      "source": "Midgard"
    },
    {
      "id": "7182",
      "question_text": "Which of the following measures would decrease the incidence of Sudden Infant Death Syndrome?",
      "option1": "Pacifier at bedtime",
      "option2": "Sleep in prone position",
      "option3": "Soft sleeping mattress",
      "option4": "Sleep position support device",
      "question_type": "pediatric",
      "correct_option": "Pacifier at bedtime",
      "source": "Midgard"
    },
    {
      "id": "7183",
      "question_text": "A 3-month-old girl presented dead to the hospital by her parents. History revealed that the girl was preterm with low birth weight and chronic lung disease. She was sleeping with her parents on their bed and both parents are smoker. Which of the following describes her death?",
      "option1": "Acute lung failure syndrome",
      "option2": "Sudden infant death syndrome",
      "option3": "Apparent life-threatening syndrome",
      "option4": "Unexpected oxygen insufficiency syndrome",
      "question_type": "pediatric",
      "correct_option": "Sudden infant death syndrome",
      "source": "Midgard"
    },
    {
      "id": "7184",
      "question_text": "Sudden infant death syndrome (SIDS) defined as unexpected death of an infant for which no adequate cause is found after postmortem examination. The incidence of SIDS has fallen during the last 20 years. Which of the following contribute the most for fallen in the incidence?",
      "option1": "Infant to be put to sleep on their back",
      "option2": "Parents avoid smoking near their infant",
      "option3": "Infant to be placed in the feet to foot position",
      "option4": "Avoid overheating by heavy wrapping or high room temperature",
      "question_type": "pediatric",
      "correct_option": "Infant to be put to sleep on their back",
      "source": "Midgard"
    },
    {
      "id": "7185",
      "question_text": "A 6-month-old infant presents to the Emergency Room with sudden apnea and color change. The mother gave history of recurrent vomiting, and multiple chest infection. On examination, he looks failing to thrive with dystonic neck posturing while crying. Which of the following considers as high-risk case for the above disease?",
      "option1": "Obese baby",
      "option2": "Preterm infant",
      "option3": "Post pertussis infection",
      "option4": "Following inguinal hernia repair",
      "question_type": "pediatric",
      "correct_option": "Preterm infant",
      "source": "Midgard"
    },
    {
      "id": "2530",
      "question_text": "A 4-month-old with Down syndrome, poor weight gain, tachypnea, systolic murmur, fixed split S2. ECG shows biventricular hypertrophy. Most likely diagnosis?",
      "option1": "Coarctation",
      "option2": "PDA",
      "option3": "VSD",
      "option4": "AV septal defect",
      "question_type": "pediatric",
      "correct_option": "AV septal defect",
      "source": "general"
    },
    {
      "id": "2531",
      "question_text": "A 4-week-old baby presents with tachypnea, cyanosis during feeding, irritability. Most common associated symptom?",
      "option1": "Cough",
      "option2": "Ascites",
      "option3": "Feeding difficulty",
      "option4": "JVD",
      "question_type": "pediatric",
      "correct_option": "Feeding difficulty",
      "source": "general"
    },
    {
      "id": "2532",
      "question_text": "A 6-month-old girl becomes cyanotic during feeding and crying. Harsh systolic murmur and single S2. Most likely diagnosis?",
      "option1": "Aortic stenosis",
      "option2": "Tetralogy of Fallot",
      "option3": "VSD",
      "option4": "TGA",
      "question_type": "pediatric",
      "correct_option": "Tetralogy of Fallot",
      "source": "general"
    },
    {
      "id": "2533",
      "question_text": "A cyanotic newborn with tachypnea, normal pulses and no murmurs. CXR shows egg-on-string heart and pulmonary congestion. Diagnosis?",
      "option1": "Tetralogy of Fallot",
      "option2": "Coarctation",
      "option3": "Transposition of great arteries",
      "option4": "PDA",
      "question_type": "pediatric",
      "correct_option": "Transposition of great arteries",
      "source": "general"
    },
    {
      "id": "2534",
      "question_text": "A 5-year-old child has loud pansystolic murmur at lower LLSB. Most likely diagnosis?",
      "option1": "ASD",
      "option2": "PDA",
      "option3": "VSD",
      "option4": "Pulmonary stenosis",
      "question_type": "pediatric",
      "correct_option": "VSD",
      "source": "general"
    },
    {
      "id": "2535",
      "question_text": "ECG finding in ostium secundum ASD?",
      "option1": "Delta waves",
      "option2": "Left axis deviation",
      "option3": "Right bundle branch block",
      "option4": "Left ventricular hypertrophy",
      "question_type": "pediatric",
      "correct_option": "Right bundle branch block",
      "source": "general"
    },
    {
      "id": "2536",
      "question_text": "Characteristic auscultatory finding in ASD?",
      "option1": "S3 gallop",
      "option2": "Fixed widely split S2",
      "option3": "Continuous murmur",
      "option4": "Systolic ejection click",
      "question_type": "pediatric",
      "correct_option": "Fixed widely split S2",
      "source": "general"
    },
    {
      "id": "2537",
      "question_text": "A 3-year-old asymptomatic child has grade 2/6 continuous murmur at upper RSB that disappears when supine. Best action?",
      "option1": "Reassurance",
      "option2": "Cardiac consult",
      "option3": "Antibiotic prophylaxis",
      "option4": "Postpone surgery",
      "question_type": "pediatric",
      "correct_option": "Reassurance",
      "source": "general"
    },
    {
      "id": "2538",
      "question_text": "Which finding in a newborn requires immediate intervention?",
      "option1": "Erupted tooth",
      "option2": "Breast enlargement",
      "option3": "Shallow sacral dimple",
      "option4": "Absent femoral pulses",
      "question_type": "pediatric",
      "correct_option": "Absent femoral pulses",
      "source": "general"
    },
    {
      "id": "2539",
      "question_text": "A 13-year-old with family history of sudden cardiac death. Normal exam. Which condition must be ruled out?",
      "option1": "Bicuspid aorta",
      "option2": "PDA",
      "option3": "VSD",
      "option4": "HCM",
      "question_type": "pediatric",
      "correct_option": "HCM",
      "source": "general"
    },
    {
      "id": "1",
      "question_text": "A patient received a severe blow on the inferolateral side of the left knee joint while playing football. Radiographic examination confirmed a fracture of the head and neck of the fibula. Which of the following nerves is most vulnerable for damage?",
      "option1": "Tibial",
      "option2": "Deep peroneal",
      "option3": "Common peroneal",
      "option4": "Superficial peroneal",
      "question_type": "surgery",
      "correct_option": "Common peroneal",
      "source": "GameBoy"
    },
    {
      "id": "2",
      "question_text": "A 19-year-old fell on an outstretched hand while playing football. Examination confirmed tenderness over the anatomic snuff box. Which of the following is the most suspected fracture?",
      "option1": "Colles",
      "option2": "Cuboid",
      "option3": "Scaphoid",
      "option4": "Hook of hamate",
      "question_type": "surgery",
      "correct_option": "Scaphoid",
      "source": "GameBoy"
    },
    {
      "id": "3",
      "question_text": "A 45-year-old man had transurethral catheterization before a long surgical procedure. Postoperatively he developed hematuria and a urethral injury is suspected. Which part of the urethra is most likely injured?",
      "option1": "Penile",
      "option2": "Prostatic",
      "option3": "Membranous",
      "option4": "Middle spongy",
      "question_type": "surgery",
      "correct_option": "Membranous",
      "source": "GameBoy"
    },
    {
      "id": "4",
      "question_text": "A patient presented after a blunt injury over the left leg. Examination confirmed sensory loss on adjacent sides of the great and second toes, and impaired dorsiflexion of the foot. Which nerve is most likely injured?",
      "option1": "Sural",
      "option2": "Saphenous",
      "option3": "Deep peroneal",
      "option4": "Posterior tibial",
      "question_type": "surgery",
      "correct_option": "Deep peroneal",
      "source": "GameBoy"
    },
    {
      "id": "5",
      "question_text": "A 61-year-old man presents to the Emergency Department with epigastric pain radiating to the back. He is a smoker with long-standing diabetes and hypertension. Abdominal exam reveals a pulsatile supra-umbilical mass. What is the most likely diagnosis?",
      "option1": "Abdominal aortic aneurysm",
      "option2": "Secondary liver metastasis",
      "option3": "Renal cell carcinoma",
      "option4": "Peri-umbilical hernia",
      "question_type": "surgery",
      "correct_option": "Abdominal aortic aneurysm",
      "source": "GameBoy"
    },
    {
      "id": "6",
      "question_text": "A patent received a severe blow on the inferolateral side of the left knee joint while playing football. Radiographic examination confirmed a fracture of the head and neck of the fibula. Which of the following nerves is most vulnerable for damaged?",
      "option1": "Tibial",
      "option2": "Deep peroneal",
      "option3": "Common peroneal",
      "option4": "Superficial peroneal",
      "question_type": "surgery",
      "correct_option": "Common peroneal",
      "source": "GameBoy"
    },
    {
      "id": "7",
      "question_text": "A 19-year-old felt on an outstretched hand while playing football. examination confirmed tenderness over the anatomic snuff box. Which of the following is the most suspected fracture?",
      "option1": "Colles",
      "option2": "Cuboi",
      "option3": "Scaphoid",
      "option4": "Hook of hamate",
      "question_type": "surgery",
      "correct_option": "Scaphoid",
      "source": "GameBoy"
    },
    {
      "id": "8",
      "question_text": "A 45-year-old man had transurethral catheterization before going for a long surgical procedure. Postoperatively he developed haematuria and a urethral injury is suspected. Which of the following is most likely injured part of urethera?",
      "option1": "Penile",
      "option2": "Prostatic",
      "option3": "Membranous",
      "option4": "Middle spongy",
      "question_type": "surgery",
      "correct_option": "Membranous",
      "source": "GameBoy"
    },
    {
      "id": "9",
      "question_text": "A patent presented after a blunt injury over the left leg. examination confirmed a sensory loss on adjacent sides of the great and second toes, and impaired dorsiflexion of the foot. Which of the following nerves is most likely injured?",
      "option1": "Sural",
      "option2": "Saphenous",
      "option3": "Deep peroneal",
      "option4": "Posterior tibial",
      "question_type": "surgery",
      "correct_option": "Deep peroneal",
      "source": "GameBoy"
    },
    {
      "id": "10",
      "question_text": "A 60-year-old man presents to the Emergency Department with epigastric pain radiating to the back. He is a smoker and has long-standing diabetes and hypertension. Abdominal examination reveals a pulsatile supra-umbilical mass. Which of the following is the most likely diagnosis?",
      "option1": "Abdominal aortic aneurysm",
      "option2": "Secondary liver metastasis",
      "option3": "Renal cell carcinoma",
      "option4": "Peri-umbilical hernia",
      "question_type": "surgery",
      "correct_option": "Abdominal aortic aneurysm",
      "source": "GameBoy"
    },
    {
      "id": "8947",
      "question_text": "A patient received a severe blow on the inferolateral side of the left knee joint while playing football. Radiographic examination confirmed a fracture of the head and neck of the fibula. Which of the following nerves is most vulnerable for damaged?",
      "option1": "Tibial",
      "option2": "Deep peroneal",
      "option3": "Common peroneal",
      "option4": "Superficial peroneal",
      "question_type": "surgery",
      "correct_option": "Common peroneal",
      "source": "Midgard"
    },
    {
      "id": "8948",
      "question_text": "A 19-year-old fell on an outstretched hand while playing football. Examination confirmed tenderness over the anatomic snuff box. Which of the following is the most suspected fracture?",
      "option1": "Colles",
      "option2": "Cuboid",
      "option3": "Scaphoid",
      "option4": "Hook of hamate",
      "question_type": "surgery",
      "correct_option": "Scaphoid",
      "source": "Midgard"
    },
    {
      "id": "8949",
      "question_text": "A 45-year-old man had transurethral catheterization before going for a long surgical procedure. Postoperatively he developed haematuria and a urethral injury is suspected. Which of the following is most likely injured part of urethra?",
      "option1": "Penile",
      "option2": "Prostatic",
      "option3": "Membranous",
      "option4": "Middle spongy",
      "question_type": "surgery",
      "correct_option": "Membranous",
      "source": "Midgard"
    },
    {
      "id": "8950",
      "question_text": "A patient presented after a blunt injury over the left leg. Examination confirmed a sensory loss on adjacent sides of the great and second toes, and impaired dorsiflexion of the foot. Which of the following nerves is most likely injured?",
      "option1": "Sural",
      "option2": "Saphenous",
      "option3": "Deep peroneal",
      "option4": "Posterior tibial",
      "question_type": "surgery",
      "correct_option": "Deep peroneal",
      "source": "Midgard"
    },
    {
      "id": "8951",
      "question_text": "A 60-year-old man presents to the Emergency Department with epigastric pain radiating to the back. He is a smoker and has long-standing diabetes and hypertension. Abdominal examination reveals a pulsatile supra-umbilical mass. Which of the following is the most likely diagnosis?",
      "option1": "Abdominal aortic aneurysm",
      "option2": "Secondary liver metastasis",
      "option3": "Renal cell carcinoma",
      "option4": "Peri-umbilical hernia",
      "question_type": "surgery",
      "correct_option": "Abdominal aortic aneurysm",
      "source": "Midgard"
    },
    {
      "id": "8952",
      "question_text": "A 45-year-old man presented to the Emergency Department complaining of lower abdominal pain for 3 days. He gave a history of being hit by a piece of wood in the same site of pain 4 days back. Examination revealed lethargic patient in pain, which was aggravated by moving his leg. there was grayish turbid semipurulent secretions from a small break in the skin of right lower quadrant (see lab result). Test Result Normal Values WBC 33.1 4.5-10.5 x 109/L Which of the following is the most appropriate next step in the management?",
      "option1": "Observation",
      "option2": "Surgical drainage",
      "option3": "CT scan abdomen",
      "option4": "Culture and sensitivity for secretions",
      "question_type": "surgery",
      "correct_option": "Surgical drainage",
      "source": "Midgard"
    },
    {
      "id": "8953",
      "question_text": "A 37-year-old man was involved in a fight and sustained a stab wound to the neck. On presentation, patient was conscious, alert. Examination showed a 2 cm wound anterior to the left ear and close to the angle of the mandible with blood ooze. which of the following is the most appropriate next step?",
      "option1": "Chest X ray",
      "option2": "Observation",
      "option3": "CTA of the neck",
      "option4": "Exploration of the wound",
      "question_type": "surgery",
      "correct_option": "CTA of the neck",
      "source": "Midgard"
    },
    {
      "id": "8954",
      "question_text": "A 19-year-old woman brought to the Emergency Department after being stabbed to the right upper quadrant. On arrival, she was conscious and oriented. Examination showed only a penetrating wound to the anterior abdominal wall at anterior axillary line just below the right costal margin. Which of the following is the most appropriate next step?",
      "option1": "Observation",
      "option2": "CT scan abdomen",
      "option3": "Ultrasound abdomen",
      "option4": "Exploratory laparotomy",
      "question_type": "surgery",
      "correct_option": "CT scan abdomen",
      "source": "Midgard"
    },
    {
      "id": "8955",
      "question_text": "A 25-year-old man brought to the Emergency Department after he was involved in motor vehicle crash, which was driving at a speed of 130 km/hour. Patient was wearing seat belt. On arrival to the Emergency Department, he was conscious, and alert (see report). Chest X-ray: Normal. Which of the following is the most appropriate next step?",
      "option1": "US abdomen",
      "option2": "CT scan abdomen",
      "option3": "Diagnostic laparoscopy",
      "option4": "Exploratory Laparotomy",
      "question_type": "surgery",
      "correct_option": "CT scan abdomen",
      "source": "Midgard"
    },
    {
      "id": "8956",
      "question_text": "A 33-year-old man was involved in a motor vehicle crash. On arrival to the Emergency Department, he was conscious and alert. Examination showed an open wound to the anterior surface of the neck with devitalized tissue. Blood pressure 100/60 mmHg Heart rate 104 /min Respiratory rate 28 /min Oxygen saturation 87% Which of the following is the most appropriate next step?",
      "option1": "Oxygen mask",
      "option2": "Tracheostomy",
      "option3": "Cricothyroidotomy",
      "option4": "Endotracheal intubation",
      "question_type": "surgery",
      "correct_option": "Endotracheal intubation",
      "source": "Midgard"
    },
    {
      "id": "482",
      "question_text": "An elderly man presents for follow-up after sustaining a road traffic accident 3 days ago. On examination, \"Battle sign\" is noted. Which of the following is the most likely cause?",
      "option1": "Le Fort fracture",
      "option2": "Mandibular fracture",
      "option3": "Fracture base of skull",
      "option4": "Fracture middle cranial fossa",
      "question_type": "surgery",
      "correct_option": "Fracture base of skull",
      "source": "general"
    },
    {
      "id": "483",
      "question_text": "A 50-year-old man becomes disoriented on the 4th post-operative day after abdominal aortic aneurysm repair. BP = 90/40 mmHg, HR = 140/min, RR = 36/min, Temp = 36.6Â°C, warm peripheries, oliguria. What type of shock is most likely?",
      "option1": "Septic",
      "option2": "Cardiogenic",
      "option3": "Hemorrhagic",
      "option4": "Anaphylactic",
      "question_type": "surgery",
      "correct_option": "Septic",
      "source": "general"
    },
    {
      "id": "484",
      "question_text": "A 20-year-old man hit by a car 2 hours ago has distended, tender abdomen. BP = 100/70 mmHg, HR = 120/min, RR = 30/min, Temp = 35Â°C, O2 sat = 90%. Most likely type of shock?",
      "option1": "Spinal",
      "option2": "Cardiogenic",
      "option3": "Hemorrhagic",
      "option4": "Anaphylactic",
      "question_type": "surgery",
      "correct_option": "Hemorrhagic",
      "source": "general"
    },
    {
      "id": "485",
      "question_text": "A 30-year-old man hit by a truck 4 hours ago has raised JVP and muffled heart sounds. BP = 90/60 mmHg, HR = 140/min, RR = 32/min, O2 sat = 85%. Most likely type of shock?",
      "option1": "Septic",
      "option2": "Cardiogenic",
      "option3": "Hemorrhagic",
      "option4": "Anaphylactic",
      "question_type": "surgery",
      "correct_option": "Cardiogenic",
      "source": "general"
    },
    {
      "id": "486",
      "question_text": "A 20-year-old patient complains of painless fresh rectal bleeding over the last 6 months. Most likely diagnosis?",
      "option1": "Anal fissure",
      "option2": "Hemorrhoids",
      "option3": "Perianal fistula",
      "option4": "Perianal abscess",
      "question_type": "surgery",
      "correct_option": "Hemorrhoids",
      "source": "general"
    },
    {
      "id": "487",
      "question_text": "A 40-year-old diabetic presents with painful perianal swelling and fever for 3 days. Labs: WBC = 16 x10â¹/L, glucose = 6.5 mmol/L. Most likely diagnosis?",
      "option1": "Anal fissure",
      "option2": "Hemorrhoids",
      "option3": "Perianal abscess",
      "option4": "Thrombosed piles",
      "question_type": "surgery",
      "correct_option": "Perianal abscess",
      "source": "general"
    },
    {
      "id": "488",
      "question_text": "A 50-year-old man developed large neck swelling with stridor and shortness of breath 5 hours post total thyroidectomy. Most appropriate next step?",
      "option1": "Tracheostomy",
      "option2": "Close observation",
      "option3": "Percutaneous drainage",
      "option4": "Bedside wound exploration",
      "question_type": "surgery",
      "correct_option": "Bedside wound exploration",
      "source": "general"
    },
    {
      "id": "489",
      "question_text": "A 60-year-old man noticed swelling at laparoscopic hernia repair site 5 days post-op. Swelling not red or hot, mildly tender. Most likely diagnosis?",
      "option1": "Seroma",
      "option2": "Hematoma",
      "option3": "Recurrence",
      "option4": "Wound infection",
      "question_type": "surgery",
      "correct_option": "Seroma",
      "source": "general"
    },
    {
      "id": "490",
      "question_text": "A 32-year-old man developed severe suprapubic pain and urinary retention 5 hours after hemorrhoidectomy. Most likely cause?",
      "option1": "Dehydration",
      "option2": "Urethral injury",
      "option3": "Inadequate analgesia",
      "option4": "Post-operative hematoma",
      "question_type": "surgery",
      "correct_option": "Inadequate analgesia",
      "source": "general"
    },
    {
      "id": "491",
      "question_text": "A 52-year-old woman presents with rapid enlargement of a neck mass and weight loss. Long-standing Hashimoto's thyroiditis. Most likely diagnosis?",
      "option1": "Hemorrhagic goiter",
      "option2": "Thyroid lymphoma",
      "option3": "Papillary carcinoma",
      "option4": "Subacute thyroiditis",
      "question_type": "surgery",
      "correct_option": "Thyroid lymphoma",
      "source": "general"
    }
  ];

export default trialQuestions;