import React, { useCallback, useEffect, useRef, useState } from 'react';
import { AppState, TouchableOpacity, View } from 'react-native';
import { router, useFocusEffect, usePathname } from 'expo-router';
import { api } from '@/lib/api';
import { isFreeTier, useAuth } from '@/lib/auth';
import { useCommon, useLang } from '@/i18n';
import { colors } from '@/theme';
import { Icon, Row, T } from '@/ui';
import { LanguageToggle } from './LanguageToggle';

/**
 * The in-app milestone feed bell. Only ever shows things that happened to this
 * student (a goal reached, a streak, a subscription about to lapse). Refetches
 * when the screen is focused and when the app returns to the foreground: the
 * events behind these rows are generated by the student's own actions.
 */
export function useNotificationCount() {
  const { user } = useAuth();
  const [unread, setUnread] = useState(0);
  const authed = !!user?.id;

  const load = useCallback(async () => {
    if (!authed) return;
    try {
      const data = await api.get('/api/notifications', { params: { limit: 1 }, timeoutMs: 10_000 });
      if (data?.success) setUnread(data.unreadCount || 0);
    } catch {
      /* the bell is ambient: a failure must never surface to the student */
    }
  }, [authed]);

  useFocusEffect(
    useCallback(() => {
      void load();
    }, [load])
  );

  useEffect(() => {
    const sub = AppState.addEventListener('change', (s) => {
      if (s === 'active') void load();
    });
    return () => sub.remove();
  }, [load]);

  return { unread, reload: load, setUnread };
}

export function NotificationBell() {
  const t = useCommon().notifications;
  const { isRTL } = useLang();
  const { unread } = useNotificationCount();
  return (
    <TouchableOpacity
      onPress={() => router.push('/notifications')}
      accessibilityRole="button"
      accessibilityLabel={unread > 0 ? `${t.label} (${unread})` : t.label}
      hitSlop={8}
      style={{
        width: 38,
        height: 38,
        borderRadius: 19,
        backgroundColor: colors.surface,
        borderWidth: 1.5,
        borderColor: colors.border,
        alignItems: 'center',
        justifyContent: 'center',
      }}
    >
      <Icon name="bell" size={18} color={colors.text} />
      {unread > 0 ? (
        <View
          style={{
            position: 'absolute',
            top: -4,
            ...(isRTL ? { left: -4 } : { right: -4 }),
            minWidth: 18,
            height: 18,
            borderRadius: 9,
            backgroundColor: colors.error,
            alignItems: 'center',
            justifyContent: 'center',
            paddingHorizontal: 4,
          }}
        >
          <T weight="bold" size={10} color={colors.white} ltr style={{ lineHeight: 14 }}>
            {unread > 9 ? '9+' : String(unread)}
          </T>
        </View>
      ) : null}
    </TouchableOpacity>
  );
}

/** Brand, bell and language switch: the top bar of every tab screen. */
export function AppBar({ title }: { title?: string }) {
  return (
    <Row
      justify="space-between"
      style={{
        paddingHorizontal: 16,
        paddingVertical: 10,
        backgroundColor: colors.surface,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
      }}
    >
      <T weight="extrabold" size={title ? 18 : 22} color={colors.primary} ltr={!title} numberOfLines={1} style={{ flexShrink: 1 }}>
        {title || 'SQB'}
      </T>
      <Row gap={8}>
        <NotificationBell />
        <LanguageToggle compact />
      </Row>
    </Row>
  );
}

// Re-fetched at most this often: it is a heads-up, not a gate.
const MIN_REFETCH_MS = 20_000;

/**
 * Slim banner with the free questions an account has left. It NEVER redirects:
 * running out of questions means quizzes stop; the account, the analytics and
 * the free lessons stay open, so there is nowhere to send anyone.
 */
export function FreeAllowanceBanner() {
  const { user, refreshSubscription } = useAuth();
  const t = useCommon();
  const pathname = usePathname();
  const last = useRef(0);

  useFocusEffect(
    useCallback(() => {
      if (Date.now() - last.current < MIN_REFETCH_MS) return;
      last.current = Date.now();
      void refreshSubscription();
    }, [refreshSubscription])
  );

  if (!isFreeTier(user)) return null;
  if (/^\/(subscribe|payment|groups)/.test(pathname)) return null;

  const remaining = user!.free_questions_remaining as number;
  const usedUp = remaining <= 0;

  return (
    <Row
      justify="space-between"
      gap={10}
      accessibilityRole="alert"
      style={{
        backgroundColor: usedUp ? colors.warningBg : colors.infoBg,
        paddingHorizontal: 14,
        paddingVertical: 8,
      }}
    >
      <Row gap={8} style={{ flex: 1 }}>
        <Icon name={usedUp ? 'lock' : 'help-circle'} size={16} color={usedUp ? colors.warning : colors.primary} />
        <T size={13} weight="semibold" color={usedUp ? colors.warning : colors.primary} style={{ flex: 1 }}>
          {usedUp ? t.freeAllowance.spent : t.freeAllowance.remaining(remaining)}
        </T>
      </Row>
      <TouchableOpacity
        onPress={() => router.push('/subscribe')}
        accessibilityRole="button"
        style={{ backgroundColor: colors.primary, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 6 }}
      >
        <T weight="bold" size={12} color={colors.white}>
          {t.freeAllowance.cta}
        </T>
      </TouchableOpacity>
    </Row>
  );
}
